app/models.py
import datetime, re

from app import db

def slugify(s):
    return re.sub('[^\w]+', '-', s).lower()

entry_tags = db.Table('entry_tags',
                      db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
                      db.Column('entry_id', db.Integer, db.ForeignKey('entry.id')))


class Entry(db.Model):

    STATUS_PUBLIC = 0
    STATUS_DRAFT = 1

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    slug = db.Column(db.String(100), unique=True)
    body = db.Column(db.Text)
    status = db.Column(db.SmallInteger, default=STATUS_PUBLIC)
    created_timestamp = db.Column(db.DateTime, default=datetime.datetime.now)
    modified_timestamp = db.Column(db.DateTime, default=datetime.datetime.now, onupdate=datetime.datetime.now)

    tags = db.relationship('Tag', secondary=entry_tags,backref=db.backref('entries', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        super(Entry, self).__init__(*args, **kwargs) #call parent constructor
        self.generate_slug()

    def generate_slug(self):
        self.slug = ''
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Entry: %s>' % self.title


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    slug = db.Column(db.String(64), unique=True)

    def __init__(self, *args, **kwargs):
        super(Tag,self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '<TAG %s>' % self.name

app/entries/forms.py
import wtforms
from wtforms.validators import DataRequired
from models import Entry

class EntryForm(wtforms.Form):
    title = wtforms.StringField('Title', validators=[DataRequired('Please enter a title')])
    body = wtforms.StringField('Body', validators=[DataRequired('Please enter body')])
    status = wtforms.SelectField('Entry status',
                                 choices=((Entry.STATUS_PUBLIC, 'Public'),
                                         (Entry.STATUS_DRAFT, 'Draft')),
                                         coerce = int)

    def save_entry(self, entry):
        self.populate_obj(entry)
        entry.generate_slug()
        return entry

app/app.py
from flask import  Flask
from flask.ext.migrate import Migrate, MigrateCommand
from flask.ext.script import Manager
from flask.ext.sqlalchemy import SQLAlchemy
from config import Configuration # import out configuration data.

app = Flask(__name__)
app.config.from_object(Configuration) #use values from out Configuration object
db = SQLAlchemy(app)
migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)

app/entries/blueprint.py
from flask import Blueprint
from helpers import object_list
from models import Entry, Tag
from entries.forms import EntryForm
from flask import render_template
from flask import request, redirect, url_for
from app import db

entries = Blueprint('entries', __name__, template_folder='templates')


@entries.route('/')
def index():
    entries = Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', entries)


@entries.route('/tags/')
def tag_index():
    tags = Tag.query.order_by(Tag.name)
    if (tags is None):
        return "No Tags"
    else:
        return object_list('entries/tag_index.html', tags)


@entries.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/tag_detail.html', entries, tag=tag)


@entries.route('/create/', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate() == False:
            return render_template('entries/create.html', form=form)
        else:
            entry = form.save_entry(Entry())
            db.session.add(entry)
            db.session.commit()
            return redirect(url_for('entries.detail', slug=entry.
            slug))
    else:
        form = EntryForm()
        return render_template('entries/create.html', form=form)


@entries.route('/<slug>')
def detail(slug):
    entry = Entry.query.filter(Entry.slug == slug).first_or_404()
    return render_template('entries/detail.html', entry=entry)


@entries.route('/<slug>/edit/', methods=['GET', 'POST'])
def edit(slug):
    entry = Entry.query.filter(Entry.slug == slug).first_or_404()
    if request.method == 'POST':
        form = EntryForm(request.form, obj=entry)
        if form.validate():
            entry = form.save_entry(entry)
            db.session.add(entry)
            db.session.commit()
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm(obj=entry)
        return render_template('entries/edit.html', entry=entry, form=form)


def entry_list(template, query, **context):
    search = request.args.get('q')
    if search:
        query = query.filter((Entry.body.contains(search))| (Entry.title.contains(search)))
    return object_list(template, query, **context)

app/main.py
from app import app, db  # import out Flask App
import models
import  views

from entries.blueprint import entries
app.register_blueprint(entries, url_prefix='/entries')
if __name__== '__main__':
    app.run()

app/views.py
from flask import render_template, request
from app import app


@app.route('/')
def homepage():
    name = request.args.get('name')
    number = request.args.get('number')
    if not name:
        name = '<unknown>'
    return render_template('Homepage.html', name=name, number=number)

app/entries/templates/entries/base_entries.html
{% extends "base.html"%}

{% block sidebar %}

    <form class="form-inline well" method="get" role="form">
        <div class="input-group">
            <input type="text" class="form-control input-xs" name="q" placeholder="Search..." value="{{ request.args.get('q', '')}}"/>
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go</button>
            </span>
        </div>
    </form>
{% endblock %}

{% block content %}
    {% include "includes/list.html" %}
    {% include "includes/page_links.html" %}
{% endblock %}

app/entries/templates/entries/create.html
{% extends "base.html" %}

{% from "macros/form_field.html" import form_field %}

{% block title %} Create new entry {% endblock %}

{% block content_title %} Create new entry {% endblock %}

{% block content %}
    <form action="{{ url_for('entries.create') }}" class="form form-horizontal" method="post">
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Create</button>
                <a href="{{ url_for('entries.index')}}" class="btn">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}

app/entries/templates/entries/detail.html
{% extends "base.html" %}
{% block title %} {{ entry.title }} {% endblock %}

{%block content_title %} {{ entry.title}} {% endblock %}

{%block sidebar %}
    <ul class="well nav nav-list">
        <li><h4>Tags</h4></li>
        {% for tag in entry.tag %}
            <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug)}}">{{ tag.name}}</a></li>
            <li><a href="{{ url_for('entries.edit', slug=entry.slug) }}">Edit</a></li>
        {% endfor %}
    </ul>
    <p>Published {{ entry.created_timestamp.strftime('%m/%d/%Y')}}</p>
    {% endblock %}

{% block content %}
 {{ entry.body}}
{% endblock %}

app/entries/templates/entries/edit.html
{% extends "base.html" %}

{% from "macros/form_field.html" import form_field %}

{% block title %} Edit {{ entry.title}} {% endblock %}

{% block content_title %} Edit {{ entry.title}} {% endblock %}

{% block content %}
    <form action="{{ url_for('entries.edit', slug=entry.slug) }}" class="form form-horizontal" method="post">
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Save</button>
                <a href="{{ url_for('entries.detail', slug=entry.slug)}}" class="btn">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}

app/entries/templates/entries/index.html
{% extends "entries/base_entries.html" %}

{% block title %} Entries {% endblock %}

{% block content_title %} Entries {% endblock %}

app/entries/templates/entries/tag_detail.html
{% extends "entries/base_entries.html" %}

{% block title %} {{tag.name}} entries {% endblock %}

{% block content_title %} {{tag.name}} entries {% endblock %}

app/entries/templates/entries/tag_index.html
{% extends "base.html" %}

{% block title %} Tags {% endblock %}

{% block content_title %} Tags {% endblock %}

{% block content %}
    <ul>
        {% for tag in object_list.items %}
        <li>
            <a href="{{ url_for('entries.tag_detail', slug=tag.slug)}}">{{ tag.name }}</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

{% block content %}
    {% include "includes/page_links.html" %}
{% endblock %}

app/entries/templates/includes/list.html
{% for entry in object_list.items %}
<p><a href="{{ url_for('entries.detail', slug=entry.slug)}}">{{entry.title}}</a></p>
{% endfor %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} | My Blog</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>
    {% block extra_styles %} {% endblock %}
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.10/js/bootstrap.min.js"></script>
    {% block extra_scripts %} {% endblock %}
</head>
<body class="{% block body_class %} {% endblock %}">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#" class="navbar-brand">{% block branding %} My Blog {% endblock %}</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('homepage') }}">Home</a></li>
                    <li><a href="{{ url_for('entries.index') }}">Blog</a></li>
                    {% block extra_nav %} {% endblock %}
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h1>{% block content_title %} {% endblock %}</h1>
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-3">
                {% block sidebar %}
                <ul class="well nav nav-stacked">
                    <li><a href="#">SideBar item</a></li>
                </ul>
                {% endblock %}
            </div>
        </div>
        <div class="row">
            <hr/>
            <footer>
                <p>&copy; your name</p>
            </footer>
        </div>
    </div>
</body>
</html>

app/templates/homepage.html
{% extends "base.html" %}

{% block content_title %} Welcome to My Blog {% endblock %}


{% block content %}
    {% if number %}

    <p>Your number is {{ number|int }}</p>

    <ul>
        {% for i in range(number|int) %}
            {% if i is divisibleby 2 %}
                <li>
                    {{ i }}
                 </li>
            {% endif %}
        {% endfor %}
    </ul>
    {% else %}
        <p>No Number specified.</p>
    {% endif %}

    <p>Your name is {{ name|default('<unknown>', True) }} </p>
{% endblock %}

app/templates/includes/page_links.html
<ul class="pagination">
    <li {% if not object_list.has_prev %} class="disabled" {% endif %}>
        {% if not object_list.has_prev %}
            <a href="./?page{{ object_list.prev_num }}">&laquo;</a>
        {% else %}
            <a href="#">&laquo;</a>
        {% endif %}
    </li>
    {% for page in object_list.iter_pages() %}
        <li>
            {% if page %}
                <a {% if page == object_list.page %} class="active" {% endif %} href="./?page= {{ page }}"> {{ page }}</a>
            {% else %}
                <a class="disabled">...</a>
            {% endif %}
        </li>
    {% endfor %}
    <li {% if not object_list.has_next %}  class="disabled" {% endif %}>
        {% if object_list.has_next %}
                <a href="./?page={{ object_list.next_num }}">&raquo;</a>
        {% else %}
            <a href="#">&raquo;</a>
        {% endif %}
    </li>
</ul>

app/templates/macros/form_field.html
{% macro form_field(field) %}
    <div class="form-group {% if field.errors %} has-error has-feedback {% endif %} ">
        {{ field.label(class='col-sm-3 control-label')}}
        <div class="col-sm-9">
            {{ field(class='form-control', **kwargs)}}
            {% if field.errors %}
                <span class="glyphicon glyphicon-warning-sign form-control-feedback">
                </span>
            {% endif %}
            {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
    </div>
{% endmacro %}